language: node_js
node_js:
  - "6.11.4"
script:
  - npm run eslint
  - npm run jshint
  - npm run jslint
  - npm run test
  - npm run checktest
  - npm run docs
after_script:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
before_script:
  - bash -xe travis/before-install.sh
  - npm install
